[bootstrap.packages]
"brew:sapling" = { os = "macos" }
"brew:restatedev/tap/restate" = { os = "macos" }
"brew:restatedev/tap/restate-server" = { os = "macos" }
"brew:restatedev/tap/restatectl" = { os = "macos" }

[dotfiles]
"~/Library/Fonts/System San Francisco Display Bold.ttf" = "~/repos/dotfiles/fonts/System San Francisco Display Bold.ttf"
"~/Library/Fonts/System San Francisco Display Regular.ttf" = "~/repos/dotfiles/fonts/System San Francisco Display Regular.ttf"
"~/Library/Fonts/System San Francisco Display Thin.ttf" = "~/repos/dotfiles/fonts/System San Francisco Display Thin.ttf"
"~/Library/Fonts/System San Francisco Display Ultralight.ttf" = "~/repos/dotfiles/fonts/System San Francisco Display Ultralight.ttf"
"~/Library/Fonts/fontawesome-webfont.ttf" = "~/repos/dotfiles/fonts/fontawesome-webfont.ttf"
"~/.gitconfig.local" = "~/repos/dotfiles/git/local-darwin.conf"
"~/.aerospace.toml" = "~/repos/dotfiles/aerospace/config.toml"
"~/Library/Preferences/sapling/sapling.conf" = "~/repos/dotfiles/sapling/macos.conf"
"~/.config/dotfiles/ssh.conf" = "~/repos/dotfiles/ssh/agent.conf"

[bootstrap.macos.keyboard]
key_repeat = 6
initial_key_repeat = 25
press_and_hold = false
automatic_capitalization = false
automatic_spelling_correction = false

[bootstrap.macos.trackpad]
tap_to_click = true

[bootstrap.macos.defaults.NSGlobalDomain]
AppleShowAllExtensions = true
NSAutomaticPeriodSubstitutionEnabled = false
"com.apple.swipescrolldirection" = false
"com.apple.trackpad.scaling" = 1.5

[bootstrap.macos.defaults."com.apple.finder"]
AppleShowAllExtensions = true

[bootstrap.macos.defaults."com.apple.WindowManager"]
HideDesktop = true

[bootstrap.macos.defaults."com.apple.menuextra.clock"]
ShowDate = 0
ShowDayOfWeek = true
ShowSeconds = true

[tasks.bootstrap]
depends = ["herdr", "screenshots"]
