" Minimal no-plugin fallback for machines without nvim.
" The real editor config lives in nvim/.

syntax on
filetype plugin indent on

set nocompatible
set encoding=utf-8
set number
set ruler
set showcmd
set laststatus=2
set backspace=indent,eol,start
set hidden
set incsearch
set hlsearch
set ignorecase
set smartcase
set autoindent
set smartindent
set tabstop=4
set shiftwidth=4
set softtabstop=4
set expandtab
set scrolloff=4
set wildmenu
set mouse=a
set nobackup
set noswapfile
